name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install Go-Camo
        run: |
          cd /tmp
          wget -q https://github.com/cactus/go-camo/releases/download/v$GOCAMO_VERSION/go-camo-$GOCAMO_VERSION.go1191.linux-amd64.tar.gz
          tar xzf go-camo-$GOCAMO_VERSION.go1191.linux-amd64.tar.gz
          cd go-camo-$GOCAMO_VERSION
          bin/go-camo -k 461fbf74af826c3a1020 &
        env:
          GOCAMO_VERSION: 2.4.8
      - run: bundle exec rake test
